from __future__ import annotations
import os
from .models import SchemaSnapshot, SyncCommand, ColumnMeta

OUTPUT_DIR = "script"

# Sort order for object types (ADD/MODIFY phase)
_ADD_ORDER = {
    "SEQUENCE": 0,
    "TABLE": 1,
    "CONSTRAINT": 2,
    "INDEX": 3,
    "FK": 4,
    "FUNCTION": 5,
    "COLUMN": 6,
}

# Sort order for DROP phase (reverse dependency)
_DROP_ORDER = {
    "FK": 0,
    "CONSTRAINT": 1,
    "INDEX": 2,
    "COLUMN": 3,
    "TABLE": 4,
    "FUNCTION": 5,
    "SEQUENCE": 6,
}


def generate_all(
    source: SchemaSnapshot,
    target: SchemaSnapshot,
    commands: list[SyncCommand],
) -> None:
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    _write_snapshot(source, os.path.join(OUTPUT_DIR, "source_schema_snapshot.txt"))
    _write_snapshot(target, os.path.join(OUTPUT_DIR, "target_schema_snapshot.txt"))
    all_failed = source.failed_statements + target.failed_statements
    _write_result_log(commands, all_failed, os.path.join(OUTPUT_DIR, "result_log.sql"))


def _write_snapshot(snap: SchemaSnapshot, path: str) -> None:
    lines = []

    # TABLES
    lines.append(f"--- TABLES ({len(snap.tables)}) ---")
    for tname in sorted(snap.tables):
        tbl = snap.tables[tname]
        lines.append(f"[Table] {tname}")
        for col in tbl.columns:
            flag = _format_column_flags(col)
            suffix = f" ({flag})" if flag else ""
            lines.append(f"  - {col.name} : {col.type_str}{suffix}")
        # Table-level constraints summary
        for con in tbl.constraints:
            cols = ", ".join(con.columns)
            name_part = f" [{con.name}]" if con.name else ""
            if con.contype == "FK" and con.ref_table:
                lines.append(f"  * {con.contype}{name_part}: ({cols}) -> {con.ref_table}")
            elif con.contype != "FK":
                lines.append(f"  * {con.contype}{name_part}: ({cols})")
    lines.append("")

    # SEQUENCES
    lines.append(f"--- SEQUENCES ({len(snap.sequences)}) ---")
    for sname in sorted(snap.sequences):
        lines.append(f"[Sequence] {sname}")
    lines.append("")

    # FUNCTIONS
    lines.append(f"--- FUNCTIONS ({len(snap.functions)}) ---")
    for fname in sorted(snap.functions):
        lines.append(f"[Function] {fname}")
    lines.append("")

    # INDEXES
    lines.append(f"--- INDEXES ({len(snap.indexes)}) ---")
    for iname in sorted(snap.indexes):
        idx = snap.indexes[iname]
        unique_str = "UNIQUE " if idx.unique else ""
        cols = ", ".join(idx.columns)
        lines.append(f"[Index] {iname} ON {idx.table_name} ({unique_str}{cols})")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _format_column_flags(col: ColumnMeta) -> str:
    if col.is_pk:
        return "PK"
    if col.is_fk:
        return "FK"
    if col.is_uk:
        return "UK"
    if col.not_null:
        return "NOT NULL"
    return ""


def _write_result_log(
    commands: list[SyncCommand],
    failed: list[tuple[str, str]],
    path: str,
) -> None:
    sorted_cmds = _sort_commands(commands)
    lines = []

    lines.append("-- DDL Diff Synchronization Script")
    lines.append("-- Generated by ddl-diff")
    lines.append("")

    for cmd in sorted_cmds:
        if cmd.is_dangerous:
            lines.append("-- [WARNING: DROP OPERATION]")
            for sql_line in cmd.sql.strip().splitlines():
                lines.append(f"-- {sql_line}")
        else:
            lines.append(f"-- [{cmd.operation}] {cmd.object_type}: {cmd.object_name}")
            if cmd.previous is not None and cmd.new is not None:
                lines.append(f"-- Previous: {cmd.previous}")
                lines.append(f"-- New: {cmd.new}")
            elif cmd.previous is not None:
                prev_lines = cmd.previous.splitlines()
                lines.append(f"-- Changed: {prev_lines[0]}")
                for extra in prev_lines[1:]:
                    lines.append(f"-- {extra}")
            lines.append(cmd.sql)
        lines.append("")

    if failed:
        lines.append("-- [PARSING FAILED STATEMENTS]")
        seen = set()
        for obj_type, name_hint in failed:
            key = (obj_type, name_hint)
            if key not in seen:
                seen.add(key)
                lines.append(f"/* PARSING FAILED: [{obj_type}] {name_hint} */")
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _sort_commands(commands: list[SyncCommand]) -> list[SyncCommand]:
    safe_cmds = [c for c in commands if not c.is_dangerous]
    danger_cmds = [c for c in commands if c.is_dangerous]

    safe_cmds.sort(key=lambda c: (
        _ADD_ORDER.get(c.object_type, 99),
        c.object_name,
    ))
    danger_cmds.sort(key=lambda c: (
        _DROP_ORDER.get(c.object_type, 99),
        c.object_name,
    ))

    return safe_cmds + danger_cmds
